config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'mypages' => 'maps#mypage', as: 'mypages'
  resources :maps, only: %i[index show] do
    resource :bookmarks, only: %i[create destroy]
    resource :counts, only: %i[create destroy]
    resources :map_comments, only: %i[create destroy]
  end
  resources :tweets, only: %i[new create index show edit destroy update] do
    resource :favorites, only: %i[create destroy]
    resources :tweet_comments, only: %i[create destroy]
  end
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  namespace :admin do
    resources :maps, only: %i[index new show create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/count.rb
class Count < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/map.rb
class Map < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :map_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :counts, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def counted_by?(user)
    counts.where(user_id: user.id).exists?
  end
end

app/models/map_comment.rb
class MapComment < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :favorites, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy

  validates :caption, length: { minimum: 0, maximum: 50 }
  validates :image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy
  has_many :map_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  has_many :bookmarks, dependent: :destroy
  has_many :counts, dependent: :destroy
  attachment :profile_image

  validates :last_name, presence: true, length: { maximum: 10 }

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def name
    last_name + first_name
  end
end

app/controllers/admin/maps_controller.rb
class Admin::MapsController < ApplicationController
  def index
    @maps = Map.all
  end

  def new
    @map = Map.new
  end

  def show
    @map = Map.find(params[:id])
  end

  def create
    @map = Map.new(map_params)
    @map.save
    redirect_to admin_map_path(@map)
  end

  def destroy
    @map = Map.find(params[:id])
    @map.destroy
    redirect_to admin_maps_path
  end

  private

  def map_params
    params.require(:map).permit(:name, :caption, :address, :latitude, :longitude)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!

  def index
    @maps = Map.all
  end

  def show
    @map = Map.find(params[:id])
    @map_comment = MapComment.new
    @counts = Count.where(map_id: @map.id)
    @map_comments = @map.map_comments.page(params[:page]).per(1)
  end

  def mypage
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.page(params[:page]).per(8)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:last_name, :first_name, :profile_image)
  end
end

app/helpers/admin/maps_helper.rb
module Admin::MapsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/counts_helper.rb
module CountsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/map_comments_helper.rb
module MapCommentsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/ralationships_helper.rb
module RalationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/maps/index.html.erb
<%= link_to '投稿',new_admin_map_path %>
<table class = "table">
  <thead>
    <tr>
      <th>コート名</th>
      <th>説明</th>
      <th>住所</th>
    </tr>
  </thead>
  <tbody>
    <%  @maps.each do |map| %>
    <tr>
      <td>
        <%= link_to admin_map_path(map) do %>
        <%= map.name %>
        <%end%>
      </td>
      <td><%= map.caption %></td>
      <td><%= map.address %></td>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/admin/maps/new.html.erb
<h1>バスケットコート登録画面</h1>

<%= form_with model: @map,url:'/admin/maps/',local:true do |f| %>
<h4>コート名</h4>
<%= f.text_field :name %>
<h4>コート説明</h4>
<%= f.text_area :caption %>
<h4>住所</h4>
<%= f.text_field :address, placeholder: "住所" %>
<%= f.submit "登録する" %>
<% end %>

app/views/admin/maps/show.html.erb
<h1>コート名</h1>
<%= @map.name %>
<%= @map.caption %>
<%= @map.address %>

<script type="text/javascript">
  function initMap() {
//latitude,longitudeから位置を指定
    var test ={lat: <%= @map.latitude %>, lng: <%= @map.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: test

    });

    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @map.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    //Map上の指定した位置にピンを挿して表示する
    var marker = new google.maps.Marker({
        position:test,
        map: map,
        title: contentString

    });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
</script>
<style type="text/css">
  #map { height: 200px;
         width: 70%;}
</style>

<div id="map"></div>
<%= link_to '削除',admin_map_path,method: :delete %>

app/views/maps/index.html.erb
<div class = "container-fluid">
  <div class = "row">
    <div class="sidebar col-sm-2 hidden-xs">
      <p>Sidebar</p>
      <p><%= link_to "ホーム",root_path, class: "fas fa-home text-light" %></p>
      <p><%= link_to "投稿",new_tweet_path, class: "fas fa-plus text-light" %></p>
      <p><%= link_to "お気に入り", mypages_path, class: "fas fa-star text-light" %></p>
      <p><%= link_to "コート",maps_path, class: "fas fa-basketball-ball text-light" %></p>
    </div>
    <div class = "col-sm-10 col-sm-offset-3">
<!-- 地名入力用のinputを追加 -->
<input id="address" type="textbox" value="東京">

<!-- buttonをクリックしたらcodeAddressを実行　-->
<input type="button" value="Encode" onclick="codeAddress()">

<div id='map'></div>
<style type="text/css">
#map { height: 600px;
         width: 100%;}
</style>

<script>
  let map
  let geocoder
  function initMap(){
    //geocoderを初期化
    //引用者注:google.maps.Geocoderインスタンスを生成
    geocoder = new google.maps.Geocoder()
    // 引用者注:google.maps.Mapインスタンスを生成することで、地図のデフォルト位置(緯度経度、ズーム)を設定
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 35.68123620000001, lng:139.7671248},
      zoom: 12,
    });

//検索フォームのボタンが押された時に実行される

//複数マーカー
<% @maps.each do |m| %>
(function(){

  //住所を変数に代入
  var contentString = '<%= link_to m.name,map_path(m) %>';

  //吹き出しの追加
  var infowindow = new google.maps.InfoWindow({
    content: contentString  //吹き出しに表示する内容
  });

  var marker = new google.maps.Marker({
    position:{lat: <%= m.latitude %>, lng: <%= m.longitude %>},
    map: map,
    title: contentString

  });
  marker.addListener('click', function() {　　//マーカをクリックしたとき
            infowindow.open(map, marker);　　//吹き出しの表示
  });

})();
<% end %>
}

function codeAddress(){
  //検索フォームの入力内容を取得
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    //該当する検索結果がヒットした時に、地図の中心を検索結果の緯度経度に更新する
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);

      //google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      //google.maps.Markerインスタンスを生成
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      //検索結果が何もなかった場合に表示
      alert('該当する結果がありませんでした：' + status);
    }
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
</div>
 </div>
</div>

app/views/maps/mypage.html.erb
<div class = "container">
  <section id = "sec01">
    <h2><span>My court</span></h2>
  </section>
<table class = "table table-bordered">
  <thead class = "bg-warning">
    <th>コート名</th>
    <th>詳細</th>
    <th>住所</th>
  </thead>
  <tbody>
    <% @bookmarks.each do |bookmark| %>
    <tr>
      <td>
        <%= link_to map_path(bookmark.map) do %>
        <%= bookmark.map.name %>
        <%end%>
      </td>
      <td><%= bookmark.map.caption %></td>
      <td><%= bookmark.map.address %></td>
    </tr>
    <%end%>
  </tbody>
</table>
</div>

app/views/maps/show.html.erb
<div class="notice"><%= notice %></div>
<div class = "container mt-5">
  <h2 class = "text-center">
    <%= @map.name %>
    <span id = "bookmark_buttons_<%= @map.id%>">
      <%= render 'bookmarks/bookmark',map: @map%>
    </span>
  </h2>
  <div class = "row">
    <table class = "table table-bordered">
        <tr>
          <th class = "bg-danger">コート名</th>
          <td><%= @map.name %></td>
        </tr>
        <tr>
          <th class = "bg-danger">詳細</th>
          <td><%= @map.caption %></td>
        </tr>
        <tr>
          <th class = "bg-danger">住所</th>
          <td><%= @map.address %></td>
        </tr>
    </table>
  </div>
  <div class = "row">
    <div class = "col-6">
      <%= render 'counts/count',map: @map%>
    </div>
    <div class = "col-6">
      <%= render 'map_comments/comment' %>
    </div>
  </div>
</div>