config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'mypages' => 'maps#mypage', as: 'mypages'
  resources :maps, only: %i[index show] do
    resource :bookmarks, only: %i[create destroy]
    resource :counts, only: %i[create destroy]
    resources :map_comments, only: %i[create destroy]
  end
  resources :tweets, only: %i[new create index show edit destroy update] do
    resource :favorites, only: %i[create destroy]
    resources :tweet_comments, only: %i[create destroy]
  end
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  namespace :admin do
    resources :maps, only: %i[index new show create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/count.rb
class Count < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/map.rb
class Map < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :map_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :counts, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def counted_by?(user)
    counts.where(user_id: user.id).exists?
  end
end

app/models/map_comment.rb
class MapComment < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :favorites, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy

  validates :caption, length: { minimum: 0, maximum: 50 }
  validates :image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy
  has_many :map_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  has_many :bookmarks, dependent: :destroy
  has_many :counts, dependent: :destroy
  attachment :profile_image

  validates :last_name, presence: true, length: { maximum: 10 }

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def name
    last_name + first_name
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!

  def index
    @maps = Map.all
  end

  def show
    @map = Map.find(params[:id])
    @map_comment = MapComment.new
    @counts = Count.where(map_id: @map.id)
    @map_comments = @map.map_comments.page(params[:page]).per(1)
  end

  def mypage
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def new
    @tweet = Tweet.new
  end

  def index
    @tweets = Tweet.all.page(params[:page]).per(16)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to user_path(@tweet.user)
    else
      render :edit
    end
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweets_path
    else
      render :new
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to request.referer
  end

  private

  def tweet_params
    params.require(:tweet).permit(:image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.page(params[:page]).per(8)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:last_name, :first_name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/counts_helper.rb
module CountsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/map_comments_helper.rb
module MapCommentsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/_modal.html.erb
<% if tweet.user == current_user %>
<!-- この要素をクリックするとモーダルが出現します -->
<span data-toggle="modal" data-target="#exampleModal">
  <i class = "fas fa-align-justify horber"></i>
</span>
<!-- モーダルの設定 -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title mx-auto" id="exampleModalLabel">投稿を編集</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <span class = "danger-font"><%= link_to "削除",tweet_path(tweet.id),method: :delete,class: "text-danger" %></span>
      </div>
      <div class = "modal-body">
        <span class = "link-font"><%= link_to "編集",edit_tweet_path(tweet.id),class: "text-dark" %></span>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary " data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<%end%>

app/views/tweets/edit.html.erb
<div classs = "container">
  <%= render 'layouts/errors', obj: @tweet %>
  <div class = "row no-gutters">
    <div class = "col-md-7 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class = "text-dark bg-lignt p4 mb-0">新規投稿</h5>
      <div class = "form-body p-4">
        <%= form_with model: @tweet,local: true do |f| %>
        <%= f.attachment_field :image %>
          <div class = "field">
            <%= f.label :"captionを書こう"%><br>
            <%= f.text_area :caption,class: "col-lg form-control" %>
        </div>
        <div class = "actions">
          <%= f.submit '新規投稿',class: "btn btn-info mt-3" %>
        </div>
        <%= link_to "キャンセル",user_path(current_user.id),class: "text-danger"%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class = "container">
  <div class = "contents-title text-center col-12">
    <section id = "sec01">
    <h2><span>tweet list</span></h2>
    </section>
    <div class ="row">
      <% @tweets.each do |tweet| %>
      <div class = "card" style = "width 16erm;">
        <div class = "card-header">
          <%= tweet.user.name %>
          <%= render 'tweets/modal',tweet: tweet%>
        </div>
        <%= link_to tweet_path(tweet.id) do %>
        <%= attachment_image_tag tweet,:image,:fill, 250,250, class: "card-img-top" %>
        <%end%>
        <div class = "card-body">
          <p>
            <%= link_to user_path(tweet.user) do %>
            <%= attachment_image_tag tweet.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
            <%end%>
          </p>
          <p class = "card-text">caption: <%= tweet.caption %></p>
          <p = "card-time">投稿日時:<%= tweet.created_at.strftime('%Y/%m/%d')%></p>
          <p>
            <span id="favorite_buttons_<%= tweet.id %>">
              <%= render 'favorites/favorite-btn', tweet: tweet%> |
            </span>
            <%= link_to tweet_path(tweet) do %>
            <i class = "far fa-comment fa-flip-horizontal"></i>コメント件数:<%= tweet.tweet_comments.count %>
            <%end%>
          </p>
          </td>
        </div>
      </div>
      <%end%>
    </div>
    <%= paginate @tweets %>
  </div>
</div>

app/views/tweets/new.html.erb
<%= render 'layouts/errors', obj: @tweet %>
<div classs = "container">
  <div class = "row no-gutters">
    <div class = "col-md-7 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class = "text-dark bg-lignt p4 mb-0">新規投稿</h5>
      <div class = "form-body p-4">
        <%= form_with model: @tweet,local: true do |f| %>
        <%= f.attachment_field :image %>
          <div class = "field">
            <%= f.label :"captionを書こう"%><br>
            <%= f.text_area :caption,class: "col-lg form-control" %>
        </div>
        <div class = "actions">
          <%= f.submit '保存',class: "btn btn-info mt-3" %>
        </div>
        <%= link_to "キャンセル",user_path(current_user.id),class: "text-danger"%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<%= render 'layouts/errors',obj: @tweet_comment %>
<main class = "container">
  <div class="tweet_comments">
  <%= render 'tweet_comments/comment',tweet: @tweet%>
  </div>
  <div class = "row">
    <div class = "col-lg-3">
    <%= form_with model:[@tweet,@tweet_comment] do |f| %>
    <%= f.text_area :comment, class: "form-control",width: 200, placeholder: "コメントをここに" %>
    <%= f.submit '送信', class: "btn btn-sm  btn-info mt-4"%>
    </div>
    <% end %>
  </div>
</main>