config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'mypages' => 'maps#mypage', as: 'mypages'
  resources :maps, only: %i[index show] do
    resource :bookmarks, only: %i[create destroy]
    resource :counts, only: %i[create destroy]
    resources :map_comments, only: %i[create destroy]
  end
  resources :tweets, only: %i[new create index show edit destroy update] do
    resource :favorites, only: %i[create destroy]
    resources :tweet_comments, only: %i[create destroy]
  end
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  namespace :admin do
    resources :maps, only: %i[index new show create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/count.rb
class Count < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/map.rb
class Map < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :map_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :counts, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def counted_by?(user)
    counts.where(user_id: user.id).exists?
  end
end

app/models/map_comment.rb
class MapComment < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :favorites, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy

  validates :caption, length: { minimum: 0, maximum: 50 }
  validates :image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy
  has_many :map_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  has_many :bookmarks, dependent: :destroy
  has_many :counts, dependent: :destroy
  attachment :profile_image

  validates :last_name, presence: true, length: { maximum: 10 }

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def name
    last_name + first_name
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!

  def index
    @maps = Map.all
  end

  def show
    @map = Map.find(params[:id])
    @map_comment = MapComment.new
    @counts = Count.where(map_id: @map.id)
    @map_comments = @map.map_comments.page(params[:page]).per(1)
  end

  def mypage
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.page(params[:page]).per(8)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:last_name, :first_name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/counts_helper.rb
module CountsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/map_comments_helper.rb
module MapCommentsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/ralationships_helper.rb
module RalationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_modal.html.erb
<!-- この要素をクリックするとモーダルが出現します -->
<% if @user == current_user %>
<button   data-toggle="modal" data-target="#exampleModal">
 <i class = "fas fa-user-cog"></i>
</button>

<!-- モーダルの設定 -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">設定</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <span class = "link-font">
           <%= link_to "編集",edit_user_path(@user),class: "text-dark" %>
          </span>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<%end%>

app/views/users/edit.html.erb
<div classs = "container">
  <%= render 'layouts/errors', obj: @user %>
  <div class = "row no-gutters">
    <div class = "col-md-7 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class = "text-dark bg-lignt p4 mb-0">プロフィール編集</h5>
      <div class = "form-body p-4">
        <%= form_with model:@user, local:true do |f| %>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></br>
        <label for="inputImage">ProfileImage</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        <div class = "field mt-4">
          <label for="inputName">Name</label>
          <%= f.text_field :last_name, autofocus: true, id:"inputName", placeholder:"性"%>
          <%= f.text_field :first_name, autofocus: true, id:"inputName", placeholder:"名前"%>
        </div>
        <div class = "actions">
          <%= f.submit '保存',class: "btn btn-info mt-3" %>
        </div>
        <%= link_to "キャンセル",user_path(current_user.id),class: "text-danger"%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
ユーザー一覧
<table>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %></td>
      <td><%= user.name %></td>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/users/show.html.erb
<div class = "container">
    <div class = "contents-title text-center col-12">
      <section id = "sec01">
        <% if @user == current_user%>
        <h2><span>My page</span></h2>
        <%else%>
        <h2><span>User</span></h2>
        <%end%>
      </section>
      <%= @user.name %>
      <% if @user == current_user %>
      <span class = "fauser">
      <%= link_to edit_user_path(@user),class: "text-dark" do %>
      <i class = "fas fa-user-cog"></i>
      <%end%>
      </span>
      <span class = "ball">
      <%= link_to  mypages_path do %>
      <i class = "fas fa-basketball-ball fa-lg size"></i>
      <%end%>
      </span>

      <%end%>
      <%= render 'relationships/follow_list'%>
      <div class = "mb-3">
      <% if current_user != @user %>
      <% if current_user.following?(@user) %>
      <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-info btn-sm" %>
      <% else %>
      <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-success btn-sm" %>
      <% end %>
      <% end %>
      </div>
      <div class = "row">
          <% @tweets.each do |tweet| %>
          <div class ="card" style="width: 16rem;">
            <div class = "card-header">
              <%= tweet.user.name %>
               <%= render 'tweets/modal',tweet: tweet%>
              </div>
              <%= attachment_image_tag tweet,:image,:fill, 250,250,class: "card-img-top"; %>
              <div class = "card-body">
                <div class = "row">
                <div class = "col-2">
                   <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
                </div>
                <div class = "col-12">
                <p class = "card-text">caption：<%= tweet.caption %></p>
                <p = "card-time">投稿日時:<%= tweet.created_at.strftime('%Y/%m/%d')%></p>
                <p>
                  <span id="favorite_buttons_<%= tweet.id %>">
                  <%= render 'favorites/favorite-btn', tweet: tweet%> |
                  </span>
                  <%= link_to tweet_path(tweet) do %>
                  <i class = "far fa-comment fa-flip-horizontal"></i>コメント件数:<%= tweet.tweet_comments.count %>
                  <%end%>
                </p>
                </div>
              </div>
             </div>
          </div>
        <%end%>
      </div>
    </div>
    <%= paginate @tweets %>
  </div>