config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'mypages' => 'maps#mypage', as: 'mypages'
  resources :maps, only: %i[index show] do
    resource :bookmarks, only: %i[create destroy]
    resource :counts, only: %i[create destroy]
    resources :map_comments, only: %i[create destroy]
  end
  resources :tweets, only: %i[new create index show edit destroy update] do
    resource :favorites, only: %i[create destroy]
    resources :tweet_comments, only: %i[create destroy]
  end
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  namespace :admin do
    resources :maps, only: %i[index new show create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/count.rb
class Count < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/map.rb
class Map < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :map_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :counts, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def counted_by?(user)
    counts.where(user_id: user.id).exists?
  end
end

app/models/map_comment.rb
class MapComment < ApplicationRecord
  belongs_to :user
  belongs_to :map
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :favorites, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy

  validates :caption, length: { minimum: 0, maximum: 50 }
  validates :image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy
  has_many :map_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  has_many :bookmarks, dependent: :destroy
  has_many :counts, dependent: :destroy
  attachment :profile_image

  validates :last_name, presence: true, length: { maximum: 10 }

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def name
    last_name + first_name
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!

  def index
    @maps = Map.all
  end

  def show
    @map = Map.find(params[:id])
    @map_comment = MapComment.new
    @counts = Count.where(map_id: @map.id)
    @map_comments = @map.map_comments.page(params[:page]).per(1)
  end

  def mypage
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/counts_helper.rb
module CountsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/map_comments_helper.rb
module MapCommentsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
<div id = "error_explanation">
  <h3><%= pluralize(obj.errors.count, "件のエラーが発生しました。")%></h3>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <%end%>
  </ul>
</div>
<%end%>

app/views/layouts/_footer.html.erb
  <footer class="footer mt-4 py-3">
    <div class="container">
      <div class="text-center">
        <p class="text-light">BasketballCommunity</p>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<header class="haikei">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <%= link_to image_tag("logo2.jpg", size: "100x100"), root_path, class:"navbar-brand p-3" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse flex-md-column" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto mb-2">
             <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "マイページ",user_path(current_user.id), class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to 'コートを探す',maps_path,class: " nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規投稿",new_tweet_path,class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "投稿一覧",tweets_path,class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト",destroy_user_session_path,method: :delete, class: "nav-link text-light" %>
        </li>
        <%else%>
        <li class="nav-item">
          <%= link_to '新規会員登録',new_user_registration_path, class: "nav-link text-light" %>
        </li>
        <li>
          <%= link_to 'ログイン',new_user_session_path, class: "nav-link text-light" %>
        </li>
        <%end%>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasketballCommunity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body  class="d-flex flex-column vh-100">
    <%= render 'layouts/header',user: @user%>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>